version: "3"

networks:
  virtual-store-api:
    external: true

services:
  app:
    container_name: virtual-store-api
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run dev
    image: virtual-store-api
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    networks:
      - virtual-store-api
    depends_on:
      - database
    ports:
      - '${PORT}:${PORT}'
    environment:
      - MYSQL_HOST=database

  database:
    container_name: db-virtual-store-api
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    expose:
      - '${MYSQL_PORT}'
    networks:
      - virtual-store-api
    command: mysqld --innodb_use_native_aio=0 --default-authentication-plugin=mysql_native_password
    volumes:
      - /db/var/lib/mysql
